# Build settings
markdown: redcarpet
highlighter: pygments

# Site settings
title: "Ahir Danışmanlık"
description: > # this means to ignore newlines until "email:"
   Kurumsal Blog Sayfası

email: info@ahir.com.tr
#blog logo
logo: "/assets/images/ahir_logo.jpg"
# blog cover
cover: "/assets/images/cover.png"

name: 'Ahir Danışmanlık'
author: 'Ahir Danışmanlık'
author_image: "/assets/images/ahir_logo.jpg"

paginate:	10

url: "http://blog.ahir.com.tr" # the base hostname & protocol for your site
baseurl: ""

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/ahirdanismanlik
    desc: Twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

  - icon:	github
    url:	https://github.com/ahirarge
    desc:	GitHub
    share_url:
    share_title:
    share_link:

gems:
  - jekyll-sitemap